# docker-compose.yml
version: "3.8"

services:
  api:
    build: .
    ports:
      - "8080:8080"
    environment:
      - ENV=production  # Adjust environment variables as needed
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
